<a href="https://colab.research.google.com/github/Temerius/ML/blob/main/course1_0_fandamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

hello everybody

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [ ]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.Tensor(7)
scalar.ndim

1

In [ ]:
tensor = torch.tensor([[[[1,2],[2,3]],[[3,4],[5,6]]]])
tensor

tensor([[[[1, 2],
          [2, 3]],

         [[3, 4],
          [5, 6]]]])

In [ ]:
tensor = torch.ones([2,3,5,4])

In [ ]:
tensor

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [ ]:
TENS1 = torch.rand(3,7)
TENSOR = torch.rand_like(TENS1)
TENS1,TENSOR

(tensor([[0.5087, 0.7197, 0.5477, 0.4358, 0.7624, 0.6184, 0.9172],
         [0.8311, 0.7235, 0.5464, 0.5799, 0.1190, 0.1160, 0.3411],
         [0.3170, 0.3618, 0.1482, 0.9664, 0.7468, 0.2685, 0.5843]]),
 tensor([[0.7261, 0.1282, 0.0429, 0.6417, 0.2887, 0.1596, 0.3505],
         [0.1905, 0.5230, 0.7792, 0.5022, 0.4176, 0.9563, 0.5398],
         [0.0715, 0.9520, 0.8624, 0.2574, 0.8815, 0.3422, 0.0871]]))

In [ ]:
TENS2 = torch.range(1,10,1)
TENS3 = torch.arange(1,10,1)

<ipython-input-9-dbf0ecba3ec4>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  TENS2 = torch.range(1,10,1)


In [ ]:
TENS2.dtype

torch.float32

In [ ]:
TENS3.dtype

torch.int64

In [ ]:
t = torch.rand([random.randint(2,7),random.randint(2,7)], dtype = torch.float16)
t

tensor([[0.3027, 0.6299],
        [0.4766, 0.7119],
        [0.8716, 0.3706],
        [0.5747, 0.9917],
        [0.9287, 0.0337],
        [0.5938, 0.8408]], dtype=torch.float16)

In [ ]:
t = torch.add(t,10)

In [ ]:
t

tensor([[10.3047, 10.6328],
        [10.4766, 10.7109],
        [10.8750, 10.3672],
        [10.5781, 10.9922],
        [10.9297, 10.0312],
        [10.5938, 10.8438]], dtype=torch.float16)

In [ ]:
t.shape

torch.Size([6, 2])

In [ ]:
t.reshape(3,4)

tensor([[10.3047, 10.6328, 10.4766, 10.7109],
        [10.8750, 10.3672, 10.5781, 10.9922],
        [10.9297, 10.0312, 10.5938, 10.8438]], dtype=torch.float16)

In [ ]:
torch.stack([t,t],dim = 0).T.shape

<ipython-input-18-b15525289325>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3614.)
  torch.stack([t,t],dim = 0).T.shape


torch.Size([2, 6, 2])

In [ ]:
array = np.random.rand(2,3)
array

array([[0.38755271, 0.46962944, 0.72887128],
       [0.60246559, 0.91509918, 0.20769387]])

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32)


In [ ]:
torch.manual_seed(42)
a = torch.rand(2,3)
torch.manual_seed(42)
b = torch.rand(2,3)
a,b

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]))

### Exercises

In [ ]:
import torch
import numpy as np
import random

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.8049, 0.4261, 0.0766, 0.6392, 0.0498, 0.0808, 0.2706],
        [0.2230, 0.8411, 0.6979, 0.2266, 0.8878, 0.6410, 0.8033],
        [0.3989, 0.5224, 0.1908, 0.8832, 0.3514, 0.6008, 0.0735],
        [0.7691, 0.7135, 0.1893, 0.1300, 0.3514, 0.5938, 0.1030],
        [0.7854, 0.6198, 0.7694, 0.7921, 0.6485, 0.0929, 0.7654],
        [0.4444, 0.6426, 0.1932, 0.0144, 0.1837, 0.5955, 0.6787],
        [0.3086, 0.6214, 0.3324, 0.9373, 0.8709, 0.2602, 0.5173]])

In [ ]:
tensor2 = torch.rand(1,7)
tensor2

tensor([[0.2182, 0.7380, 0.5493, 0.1180, 0.2979, 0.8729, 0.7419]])

In [ ]:
torch.mm(tensor1, tensor2.T).squeeze().unsqueeze(dim = 0)

tensor([[0.8937, 2.4994, 1.3652, 1.5132, 1.9871, 1.7570, 1.6895]])

In [ ]:
torch.manual_seed(0)
tensor1_1 = torch.rand(7,7)
tensor1_1

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
torch.manual_seed(0)
tensor2_2 = torch.rand(1,7)
tensor2_2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [ ]:
torch.mm(tensor2_2, tensor1_1).squeeze()

tensor([1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752])

In [ ]:
torch.manual_seed(42)
tensor3 = torch.rand(2,3).to(device) if device == 'cuda' else torch.rand(2,3)
tensor3.device

device(type='cuda', index=0)

In [ ]:
! nvidia-smi

Sun Jan 28 14:43:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0              27W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
torch.manual_seed(42)
tensor4 = torch.rand(2,3).to(device) if device == 'cuda' else torch.rand(2,3)
tensor4.device

device(type='cuda', index=0)

In [ ]:
result_tensor = torch.mm(tensor3, tensor4.reshape(3,2))
result_tensor

tensor([[1.2782, 1.9151],
        [1.2305, 1.6134]], device='cuda:0')

In [ ]:
print(f"Max = {result_tensor.max()}")
print(f"Min = {result_tensor.min()}")
print(f"ArgMax = {result_tensor.argmax()}")
print(f"ArgMin = {result_tensor.argmin()}")

Max = 1.915109395980835
Min = 1.2304728031158447
ArgMax = 1
ArgMin = 2


In [ ]:
torch.rand(1,1,1,10).squeeze().shape

torch.Size([10])

In [ ]:
tensor = torch.randn(1,2)